### ISSUE TITLE
Get cf-uaac installed in Windows 10/2016

### ISSUE THREAD

**Issue by pacphi** [pacphi/pcftools#3]
`RubyInstaller for Windows` seems to be the recommended option to install Ruby on Windows, here https://rubyinstaller.org.  

However, while I have experimented with getting it installed manually on a Windows 10 VM, I cannot get `cf-uaac` installed successfully; neither with 

```
gem install cf-uaac
```

nor

```
bundle install
gem build cf-uaac.gemspec
gem install cf-uaac*.gem
```

What I see on invoking `uaac` from the command line is ...
```
C:\Users\cphillipson\Documents\development\pivotal\cf-uaac>uaac
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        22: from C:/Ruby26-x64/bin/uaac:23:in `<main>'
        21: from C:/Ruby26-x64/bin/uaac:23:in `load'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/bin/uaac:17:in `<top (required)>'
        19: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        18: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaac_cli.rb:15:in `<top (required)>'
        16: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        15: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/cli/runner.rb:15:in `<top (required)>'
        13: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        12: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/cli/token.rb:17:in `<top (required)>'
        10: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/stub/server.rb:14:in `<top (required)>'
         7: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/rubyeventmachine (LoadError)
        23: from C:/Ruby26-x64/bin/uaac:23:in `<main>'
        22: from C:/Ruby26-x64/bin/uaac:23:in `load'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/bin/uaac:17:in `<top (required)>'
        20: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaac_cli.rb:15:in `<top (required)>'
        17: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/cli/runner.rb:15:in `<top (required)>'
        14: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/cli/token.rb:17:in `<top (required)>'
        11: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/stub/server.rb:14:in `<top (required)>'
         8: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         7: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         5: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
         3: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/rubyeventmachine (LoadError)
        23: from C:/Ruby26-x64/bin/uaac:23:in `<main>'
        22: from C:/Ruby26-x64/bin/uaac:23:in `load'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/bin/uaac:17:in `<top (required)>'
        20: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaac_cli.rb:15:in `<top (required)>'
        17: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/cli/runner.rb:15:in `<top (required)>'
        14: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/cli/token.rb:17:in `<top (required)>'
        11: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/stub/server.rb:14:in `<top (required)>'
         8: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         7: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
         6: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/rubyeventmachine (LoadError)
        24: from C:/Ruby26-x64/bin/uaac:23:in `<main>'
        23: from C:/Ruby26-x64/bin/uaac:23:in `load'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/bin/uaac:17:in `<top (required)>'
        21: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        20: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaac_cli.rb:15:in `<top (required)>'
        18: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/cli/runner.rb:15:in `<top (required)>'
        15: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/cli/token.rb:17:in `<top (required)>'
        12: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cf-uaac-4.1.0/lib/uaa/stub/server.rb:14:in `<top (required)>'
         9: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         8: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
         7: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         5: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
         3: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/rubyeventmachine (LoadError)
```

**Comment by pacphi** [comment]
This post's suggestion was the answer: https://github.com/oneclick/rubyinstaller2/issues/96#issuecomment-434619796.
